CREATE TABLE `streamer`
(
    `id`               bigint       NOT NULL AUTO_INCREMENT COMMENT '主键，自增ID',
    `gmt_create`       datetime     NOT NULL                                         DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    `gmt_modified`     datetime     NOT NULL                                         DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录修改时间',
    `name`             varchar(255) NOT NULL COMMENT '直播名称',
    `room_url`         varchar(255)                                                  DEFAULT NULL COMMENT '直播间地址',
    `record_type`      varchar(50)                                                   DEFAULT NULL COMMENT '录制类型, vod为录像，living为直播',
    `last_record_time` datetime                                                      DEFAULT NULL COMMENT '上次录制时间, vod是上一次视频上传的时间, living是开始的录制时间',
    `expire_time`      datetime                                                      DEFAULT NULL COMMENT '录播过期时间',
    `last_vod_cnt`     int                                                           DEFAULT NULL COMMENT 'vod是录制最近的视频的数量',
    `seg_merge_cnt`    int                                                           DEFAULT NULL COMMENT '多少视频分片合成一个视频',
    `template_title`   varchar(255)                                                  DEFAULT NULL COMMENT '视频标题模板',
    `cover_path`       varchar(255)                                                  DEFAULT NULL COMMENT '视频封面',
    `upload_platforms` varchar(255)                                                  DEFAULT NULL COMMENT '上传平台',
    `process_plugins`  varchar(255)                                                  DEFAULT NULL COMMENT '处理插件',
    `tags`             varchar(255)                                                  DEFAULT NULL COMMENT '标签',
    `desc`             text COMMENT '视频描述',
    `extra`            text COMMENT '额外信息',
    `env`              varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'default',
    `max_merge_size`   int                                                           DEFAULT NULL COMMENT '单个文件最大大小(MB)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_name` (`name`),
    KEY                `idx_env` (`env`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='录播信息表'