FROM linuxserver/ffmpeg:7.0.2

# 更新包列表，安装 pip 和 python3-venv，并清理缓存
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-pip \
    python3-venv \
    openjdk-8-jre \
    fonts-noto-cjk \
#    fonts-wqy-microhei \
#    fonts-wqy-zenhei \
    libxkbcommon0 \
    libgbm1 \
    libgtk-3-0t64 \
    libcairo-gobject2 && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# 更新字头
RUN fc-cache -f -v

# 创建 Python 虚拟环境并安装 streamlink
RUN python3 -m venv /opt/myenv && \
    /opt/myenv/bin/pip install --no-cache-dir streamlink

# 将虚拟环境路径添加到 PATH
ENV PATH="/opt/myenv/bin:$PATH"