FROM python:3.10

WORKDIR /app

# 复制 Python 脚本和模型到容器中
COPY paddle-vision.py /app/paddle-vision.py
COPY models /app/models

# 安装必要的系统依赖
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    libgtk2.0-0 \
    libjpeg62-turbo-dev \
    libpng-dev \
    && rm -rf /var/lib/apt/lists/*



RUN pip install --no-cache-dir \
    numpy \
    fastapi \
    uvicorn \
    opencv-python \
    fastdeploy-python \
    pillow \
    python-multipart \
    -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html

EXPOSE 5000

CMD ["python", "-u", "paddle-vision.py"]