FROM alpine:latest

RUN apk update && \
    apk add --no-cache shadowsocks-libev bash

# 创建配置目录
RUN mkdir -p /etc/shadowsocks-libev
COPY ./proxy-config.json /etc/shadowsocks-libev/config.json

EXPOSE 1080

CMD ["ss-local", "-c", "/etc/shadowsocks-libev/config.json"]