FROM alpine:latest

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache shadowsocks-libev bash

# 创建配置目录
RUN mkdir -p /etc/shadowsocks-libev
COPY ./proxy-config.json /etc/shadowsocks-libev/config.json

EXPOSE 1080

CMD ["ss-local", "-c", "/etc/shadowsocks-libev/config.json"]